spring.application.name=uistify-backend
spring.config.import=optional:file:env.properties
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

bucket.name=${BUCKET_NAME:bucket}
access.key=${ACCESS_KEY:key}
secret.key=${SECRET_KEY:secreto}
region.key=${REGION:us-east-1}
url.minio=${URL_MINIO:http://localhost}