spring.application.name=uistify-backend
spring.config.import=optional:file:env.properties
spring.datasource.url=jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
